server.port=8081
spring.application.name=ms-usuarios

# ==========================================
# CONFIGURACION DE BASE DE DATOS (PostgreSQL)
# ==========================================
# Asegurate de que el puerto 5432 es el correcto y la base de datos se llame 'gamerbox_usuarios'
spring.datasource.url=jdbc:postgresql://localhost:5432/gamerbox_usuarios
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de IntelliJ las consultas SQL que Spring esta ejecutando (muy util para depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Especificamos el dialecto para que Spring optimice las consultas a PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect